package catgoryapp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import org.springframework.transaction.annotation.Transactional;

import catgoryapp.catgorydao.Catgory;
import catgoryapp.catgorydao.CatgoryRepository;
import catgoryapp.inventorydao.Inventory;
import catgoryapp.inventorydao.InventoryRepository;
import java.util.*;

@RestController    // This means that this class is a Controller
public class MainController{
  @Autowired // This means to get the beans
           // Which is auto-generated by Spring, we will use it to handle the data
  private CatgoryRepository  catreop;
  @Autowired
  private InventoryRepository invtreop;
  @CrossOrigin
  @GetMapping(path="/all")
  public @ResponseBody List<Catgory> getAllCatgory() {
		// This returns a JSON or XML with the users
		return catreop.findAll();
	}
  private boolean findparent(Catgory curr,List<Catgory> catlist,Integer pid){
    while(curr.getPID()!=null){
      if(curr.getPID()==pid){
        return true;
      }
      curr= catreop.getById(curr.getPID());
    }
    return false;
  }

  @CrossOrigin
  @GetMapping("/find")
  public List<Catgory> findCatgory(@RequestParam Integer id){
    List<Catgory> catlist=catreop.findAll();

    List<Catgory> solu=new ArrayList<Catgory>();
    solu.add(catreop.getById(id));
    for(Catgory c: catlist){
      if(findparent(c,catlist,id)==true){
        solu.add(c);
      }
    }
    return solu;
  }

  @CrossOrigin
  @GetMapping("/list")
  public List<Inventory> listByCatgory(@RequestParam Integer id){
      List<Catgory> slelectd=findCatgory(id);
      List<Inventory> invlist=invtreop.findAll();
      List<Inventory> solu=new ArrayList<Inventory>();
      for(Inventory i:invlist){
        for(Catgory c: slelectd){
          if(i.getCatgoryId()==c.getID()){
            solu.add(i);
          }
        }
      }
    return solu;
  }

  @CrossOrigin
  @Transactional
  @GetMapping("/delete")
  public String deleteInvById(@RequestParam Integer id){
      invtreop.deleteInvById(id);
      return "deleted";
  }
}
